// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infrastructure/core/local/records/app_settings_record.dart';
import 'infrastructure/core/local/records/user_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4753593989117032601),
    name: 'UserRecord',
    lastPropertyId: const obx_int.IdUid(4, 8005673301360801686),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2574681842802853139),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1325078427106921435),
        name: 'remoteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 6218771340300999518),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5022952648692684586),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8005673301360801686),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4174291376144611737),
    name: 'AppSettingsRecord',
    lastPropertyId: const obx_int.IdUid(3, 3503005441903137361),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4291181846982233782),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7417587751224718738),
        name: 'themeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3503005441903137361),
        name: 'syncToken',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4174291376144611737),
    lastIndexId: const obx_int.IdUid(1, 6218771340300999518),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserRecord: obx_int.EntityDefinition<UserRecord>(
      model: _entities[0],
      toOneRelations: (UserRecord object) => [],
      toManyRelations: (UserRecord object) => {},
      getId: (UserRecord object) => object.id,
      setId: (UserRecord object, int id) {
        object.id = id;
      },
      objectToFB: (UserRecord object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        final emailOffset = fbb.writeString(object.email);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = UserRecord(
          remoteId: remoteIdParam,
          email: emailParam,
          name: nameParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AppSettingsRecord: obx_int.EntityDefinition<AppSettingsRecord>(
      model: _entities[1],
      toOneRelations: (AppSettingsRecord object) => [],
      toManyRelations: (AppSettingsRecord object) => {},
      getId: (AppSettingsRecord object) => object.id,
      setId: (AppSettingsRecord object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingsRecord object, fb.Builder fbb) {
        final themeModeOffset = fbb.writeString(object.themeMode);
        final syncTokenOffset = object.syncToken == null
            ? null
            : fbb.writeString(object.syncToken!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, themeModeOffset);
        fbb.addOffset(2, syncTokenOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final themeModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final syncTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = AppSettingsRecord(
          id: idParam,
          themeMode: themeModeParam,
          syncToken: syncTokenParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserRecord] entity fields to define ObjectBox queries.
class UserRecord_ {
  /// See [UserRecord.id].
  static final id = obx.QueryIntegerProperty<UserRecord>(
    _entities[0].properties[0],
  );

  /// See [UserRecord.remoteId].
  static final remoteId = obx.QueryStringProperty<UserRecord>(
    _entities[0].properties[1],
  );

  /// See [UserRecord.email].
  static final email = obx.QueryStringProperty<UserRecord>(
    _entities[0].properties[2],
  );

  /// See [UserRecord.name].
  static final name = obx.QueryStringProperty<UserRecord>(
    _entities[0].properties[3],
  );
}

/// [AppSettingsRecord] entity fields to define ObjectBox queries.
class AppSettingsRecord_ {
  /// See [AppSettingsRecord.id].
  static final id = obx.QueryIntegerProperty<AppSettingsRecord>(
    _entities[1].properties[0],
  );

  /// See [AppSettingsRecord.themeMode].
  static final themeMode = obx.QueryStringProperty<AppSettingsRecord>(
    _entities[1].properties[1],
  );

  /// See [AppSettingsRecord.syncToken].
  static final syncToken = obx.QueryStringProperty<AppSettingsRecord>(
    _entities[1].properties[2],
  );
}
