import 'dart:convert';
import 'package:relic/relic.dart';
import '../../domain/entities/provider_config.dart';
import '../../application/containers/metadata_usecases.dart';
import '../../service_locator.dart';
import '../../infrastructure/connectors/phorge/phorge_client.dart';
import '../middlewares/auth_middleware.dart';

/// [ARCH: PRESENTATION_CONTROLLER]
/// ROLE: Controller for Platform Metadata and Configuration.
/// CONTRACT: Maps HTTP requests for provider settings and dynamic metadata to [MetadataUseCases].
/// CONSTRAINTS: Purely for data delivery. Handles user context resolution from [userIdProperty].
class MetadataController {
  final MetadataUseCases _metadata = sl<MetadataUseCases>();

  Future<Response> getProviders(Request request) async {
    final userId = userIdProperty.get(request);
    print('User $userId fetching metadata...');

    try {
      final metadata = await _metadata.getProviderMetadata.execute(userId);
      final jsonList = metadata.map((m) => m.toMap()).toList();

      return Response.ok(
        body: Body.fromString(
          jsonEncode({
            'data': jsonList,
            'meta': {
              'dataType': 'list:provider_metadata',
              'timestamp': DateTime.now().toIso8601String(),
            },
          }),
          mimeType: MimeType.json,
        ),
      );
    } catch (e) {
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch metadata',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> getConfigs(Request request) async {
    try {
      final configs = await _metadata.getProviderConfigs.execute();
      final jsonList = configs.map((c) => c.toMap()).toList();
      final statusResult = await _metadata.getSystemStatus.execute();
      final isSystemConfigured = statusResult.getOrElse((_) => false);

      return Response.ok(
        body: Body.fromString(
          jsonEncode({
            'data': jsonList,
            'meta': {
              'dataType': 'list:provider_config',
              'isSystemConfigured': isSystemConfigured,
              'timestamp': DateTime.now().toIso8601String(),
            },
          }),
          mimeType: MimeType.json,
        ),
      );
    } catch (e) {
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch provider configurations',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> getStatus(Request request) async {
    try {
      final statusResult = await _metadata.getSystemStatus.execute();
      final isSystemConfigured = statusResult.getOrElse((_) => false);

      return Response.ok(
        body: Body.fromString(
          jsonEncode({
            'data': {
              'isSystemConfigured': isSystemConfigured,
            },
            'meta': {
              'dataType': 'system_status',
              'timestamp': DateTime.now().toIso8601String(),
            },
          }),
          mimeType: MimeType.json,
        ),
      );
    } catch (e) {
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch system status',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> saveConfig(Request request) async {
    try {
      final bodyStr = await request.readAsString();
      final data = jsonDecode(bodyStr) as Map<String, dynamic>;
      
      // Use the class fromMap method generated by dart_mappable
      final config = ProviderConfigMapper.fromMap(data);

      final result = await _metadata.saveProviderConfig.execute(config);

      return result.fold(
        (failure) => Response.internalServerError(
          body: Body.fromString(
            jsonEncode({'error': failure.message}),
            mimeType: MimeType.json,
          ),
        ),
        (savedConfig) => Response.ok(
          body: Body.fromString(
            jsonEncode({'data': savedConfig.toMap()}),
            mimeType: MimeType.json,
          ),
        ),
      );
    } catch (e) {
      return Response.badRequest(
        body: Body.fromString(
          jsonEncode({'error': 'Invalid request body', 'details': e.toString()}),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> testConfig(Request request) async {
    try {
      final bodyStr = await request.readAsString();
      final data = jsonDecode(bodyStr) as Map<String, dynamic>;
      final config = ProviderConfigMapper.fromMap(data);

      print('TESTING CONFIG: ${config.name} at ${config.baseUrl}');

      if (config.id == 'phorge' || config.id == 'phabricator') {
        final apiToken = config.settings['api.token'] ?? config.settings['apiToken'];
        
        if (apiToken == null || apiToken.toString().isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({'error': 'Connection failed', 'details': 'API Token is missing'}),
              mimeType: MimeType.json,
            ),
          );
        }

        final client = PhorgeClient(
          baseUrl: config.baseUrl,
          apiToken: apiToken.toString(),
        );

        try {
          final result = await client.call('user.whoami', {}).timeout(const Duration(seconds: 10));
          client.dispose();
          
          final userName = result['userName'] ?? result['realName'] ?? result['value'] ?? 'Unknown User';
          final phid = result['phid'] ?? result['phid'] ?? 'Unknown PHID';

          return Response.ok(
            body: Body.fromString(
              jsonEncode({
                'data': {
                  'status': 'connected',
                  'message': 'Successfully connected as $userName ($phid)',
                },
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          client.dispose();
          String details = e.toString();
          
          if (details.contains('ERR-CONDUIT-AUTH')) {
            details = 'Invalid API Token (ERR-CONDUIT-AUTH)';
          } else if (details.contains('Failed host lookup')) {
            details = 'Could not resolve host: ${config.baseUrl}. Check the URL and DNS settings.';
          } else if (details.contains('Connection refused')) {
            details = 'Connection refused at ${config.baseUrl}. The server might be down or blocked by a firewall.';
          } else if (details.contains('TimeoutException')) {
            details = 'Connection timed out. Check your network or Phorge server status.';
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': details,
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      // Fallback for other providers (Generic ping or mock)
      await Future.delayed(const Duration(seconds: 1));
      
      bool success = true;
      String? errorMessage;

      if (!config.isActive) {
        success = false;
        errorMessage = 'Provider is not active';
      } else if (config.baseUrl.isEmpty) {
        success = false;
        errorMessage = 'Base URL is missing';
      }

      if (success) {
        return Response.ok(
          body: Body.fromString(
            jsonEncode({
              'data': {'status': 'connected', 'message': 'Successfully pinged ${config.name}'},
            }),
            mimeType: MimeType.json,
          ),
        );
      } else {
        return Response.badRequest(
          body: Body.fromString(
            jsonEncode({
              'error': 'Connection failed',
              'details': errorMessage,
            }),
            mimeType: MimeType.json,
          ),
        );
      }
    } catch (e) {
      return Response.badRequest(
        body: Body.fromString(
          jsonEncode({'error': 'Invalid request body', 'details': e.toString()}),
          mimeType: MimeType.json,
        ),
      );
    }
  }
}
