import 'dart:convert';
import 'package:relic/relic.dart';
import 'package:http/http.dart' as http;
import '../../domain/entities/provider/provider_config.dart';
import '../../application/containers/metadata_usecases.dart';
import '../../infrastructure/sources/discord/discord_gateway_service.dart';
import '../../service_locator.dart';
import '../../infrastructure/protocols/conduit/conduit_protocol.dart';
import '../../infrastructure/protocols/conduit/http_conduit_protocol.dart';
import '../middlewares/auth_middleware.dart';

/// [ARCH: PRESENTATION_CONTROLLER]
/// ROLE: Controller for Platform Metadata and Configuration.
/// CONTRACT: Maps HTTP requests for provider settings and dynamic metadata to [MetadataUseCases].
/// CONSTRAINTS: Purely for data delivery. Handles user context resolution from [userIdProperty].
class MetadataController {
  final MetadataUseCases _metadata = sl<MetadataUseCases>();

  Future<Response> getProviders(Request request) async {
    final userId = userIdProperty.get(request);
    final result = await _metadata.getProviderMetadata.execute(userId);
    return result.fold(
      (failure) => Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch metadata',
            'details': failure.message,
          }),
          mimeType: MimeType.json,
        ),
      ),
      (metadata) {
        final jsonList = metadata.map((m) => m.toMap()).toList();
        return Response.ok(
          body: Body.fromString(
            jsonEncode({
              'data': jsonList,
              'meta': {
                'dataType': 'list:provider_metadata',
                'timestamp': DateTime.now().toIso8601String(),
              },
            }),
            mimeType: MimeType.json,
          ),
        );
      },
    );
  }

  Future<Response> getCapabilities(Request request) async {
    try {
      final capabilities = await _metadata.getProviderCapabilities.execute();
      return Response.ok(
        body: Body.fromString(
          jsonEncode({
            'data': capabilities,
            'meta': {
              'dataType': 'list:provider_capability',
              'timestamp': DateTime.now().toIso8601String(),
            },
          }),
          mimeType: MimeType.json,
        ),
      );
    } catch (e) {
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch provider capabilities',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> getConfigs(Request request) async {
    final result = await _metadata.getProviderConfigs.execute();
    if (result.isLeft()) {
      final failure = result.getLeft().toNullable()!;
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch provider configurations',
            'details': failure.message,
          }),
          mimeType: MimeType.json,
        ),
      );
    }
    final configs = result.getRight().toNullable()!;
    final jsonList = configs.map((c) => c.toMap()).toList();
    final statusResult = await _metadata.getSystemStatus.execute();
    final isSystemConfigured = statusResult.getOrElse((_) => false);

    return Response.ok(
      body: Body.fromString(
        jsonEncode({
          'data': jsonList,
          'meta': {
            'dataType': 'list:provider_config',
            'isSystemConfigured': isSystemConfigured,
            'timestamp': DateTime.now().toIso8601String(),
          },
        }),
        mimeType: MimeType.json,
      ),
    );
  }

  Future<Response> getStatus(Request request) async {
    try {
      final statusResult = await _metadata.getSystemStatus.execute();
      final isSystemConfigured = statusResult.getOrElse((_) => false);

      return Response.ok(
        body: Body.fromString(
          jsonEncode({
            'data': {
              'isSystemConfigured': isSystemConfigured,
            },
            'meta': {
              'dataType': 'system_status',
              'timestamp': DateTime.now().toIso8601String(),
            },
          }),
          mimeType: MimeType.json,
        ),
      );
    } catch (e) {
      return Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch system status',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> saveConfig(Request request) async {
    try {
      final bodyStr = await request.readAsString();
      final data = jsonDecode(bodyStr) as Map<String, dynamic>;

      // Use the class fromMap method generated by dart_mappable
      final config = ProviderConfigMapper.fromMap(data);

      final result = await _metadata.saveProviderConfig.execute(config);

      return result.fold(
        (failure) => Response.internalServerError(
          body: Body.fromString(
            jsonEncode({'error': failure.message}),
            mimeType: MimeType.json,
          ),
        ),
        (savedConfig) {
          if (savedConfig.id == 'discord') {
            sl<DiscordGatewayService>().reload().catchError((e) {
              print('Error reloading DiscordGatewayService: $e');
            });
          }
          return Response.ok(
            body: Body.fromString(
              jsonEncode({'data': savedConfig.toMap()}),
              mimeType: MimeType.json,
            ),
          );
        },
      );
    } catch (e) {
      return Response.badRequest(
        body: Body.fromString(
          jsonEncode({
            'error': 'Invalid request body',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> testConfig(Request request) async {
    try {
      final bodyStr = await request.readAsString();
      final data = jsonDecode(bodyStr) as Map<String, dynamic>;
      final config = ProviderConfigMapper.fromMap(data);

      print('TESTING CONFIG: ${config.name} at ${config.baseUrl}');

      if (config.id == 'phorge' || config.id == 'phabricator') {
        final apiToken =
            config.settings['api.token'] ?? config.settings['apiToken'];

        if (apiToken == null || apiToken.toString().isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'API Token is missing',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final ConduitProtocol client = HttpConduitProtocol(
          baseUrl: config.baseUrl,
          apiToken: apiToken.toString(),
        );

        try {
          final result = await client
              .call('user.whoami', {})
              .timeout(const Duration(seconds: 10));
          client.dispose();

          final userName =
              result['userName'] ??
              result['realName'] ??
              result['value'] ??
              'Unknown User';
          final phid = result['phid'] ?? result['phid'] ?? 'Unknown PHID';

          return Response.ok(
            body: Body.fromString(
              jsonEncode({
                'data': {
                  'status': 'connected',
                  'message': 'Successfully connected as $userName ($phid)',
                },
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          client.dispose();
          String details = e.toString();

          if (details.contains('ERR-CONDUIT-AUTH')) {
            details = 'Invalid API Token (ERR-CONDUIT-AUTH)';
          } else if (details.contains('Failed host lookup')) {
            details =
                'Could not resolve host: ${config.baseUrl}. Check the URL and DNS settings.';
          } else if (details.contains('Connection refused')) {
            details =
                'Connection refused at ${config.baseUrl}. The server might be down or blocked by a firewall.';
          } else if (details.contains('TimeoutException')) {
            details =
                'Connection timed out. Check your network or Phorge server status.';
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({'error': 'Connection failed', 'details': details}),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'github') {
        final token =
            (config.settings['api.token'] ?? config.settings['token'] ?? '')
                .toString()
                .trim();
        if (token.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'GitHub token is missing',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final configuredApiBaseUrl = (config.settings['apiBaseUrl'] ?? '')
            .toString()
            .trim();
        final apiBaseUrl =
            (configuredApiBaseUrl.isEmpty
                    ? 'https://api.github.com'
                    : configuredApiBaseUrl)
                .replaceAll(RegExp(r'/+$'), '');
        final uri = Uri.parse('$apiBaseUrl/user');

        try {
          final response = await http
              .get(
                uri,
                headers: {
                  'Accept': 'application/vnd.github+json',
                  'Authorization': 'Bearer $token',
                  'User-Agent': 'dab-api',
                  'X-GitHub-Api-Version': '2022-11-28',
                },
              )
              .timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            final login = body['login']?.toString() ?? 'unknown';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected as $login',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details':
                    'GitHub API returned ${response.statusCode}. Verify token and API base URL.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'GitHub connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'bitbucket') {
        final username = (config.settings['username'] ?? '').toString().trim();
        final secret =
            (config.settings['apiToken'] ??
                    config.settings['appPassword'] ??
                    config.settings['token'] ??
                    '')
                .toString()
                .trim();
        if (username.isEmpty || secret.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Bitbucket username or app password is missing',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final uri = Uri.parse('https://api.bitbucket.org/2.0/user');
        try {
          final basic = base64Encode(utf8.encode('$username:$secret'));
          final response = await http
              .get(
                uri,
                headers: {
                  'Authorization': 'Basic $basic',
                  'Accept': 'application/json',
                },
              )
              .timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            final display = body['display_name']?.toString() ?? 'unknown';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected as $display',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details':
                    'Bitbucket API returned ${response.statusCode}. Verify username and app password.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Bitbucket connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'slack') {
        final token =
            (config.settings['botToken'] ??
                    config.settings['api.token'] ??
                    config.settings['token'] ??
                    '')
                .toString()
                .trim();
        if (token.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Slack bot token is missing',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final apiBaseUrl =
            ((config.settings['apiBaseUrl'] ?? '').toString().trim().isEmpty
                    ? 'https://slack.com/api'
                    : (config.settings['apiBaseUrl'] ?? '').toString().trim())
                .replaceAll(RegExp(r'/+$'), '');
        final uri = Uri.parse('$apiBaseUrl/auth.test');
        try {
          final response = await http
              .post(
                uri,
                headers: {
                  'Authorization': 'Bearer $token',
                  'Content-Type': 'application/json; charset=utf-8',
                },
              )
              .timeout(const Duration(seconds: 10));

          if (response.statusCode != 200) {
            return Response.badRequest(
              body: Body.fromString(
                jsonEncode({
                  'error': 'Connection failed',
                  'details': 'Slack API returned ${response.statusCode}.',
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          final body = jsonDecode(response.body) as Map<String, dynamic>;
          if (body['ok'] != true) {
            final error = body['error']?.toString() ?? 'unknown_error';
            return Response.badRequest(
              body: Body.fromString(
                jsonEncode({
                  'error': 'Connection failed',
                  'details': 'Slack auth.test failed: $error',
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          final teamName = body['team']?.toString() ?? 'unknown workspace';
          return Response.ok(
            body: Body.fromString(
              jsonEncode({
                'data': {
                  'status': 'connected',
                  'message':
                      'Successfully connected to Slack workspace $teamName',
                },
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Slack connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'jira') {
        final apiToken = (config.settings['apiToken'] ?? config.settings['api.token'] ?? config.settings['token'] ?? '').toString().trim();
        final email = (config.settings['email'] ?? '').toString().trim();
        var instanceUrl = (config.settings['instanceUrl'] ?? config.baseUrl ?? '').toString().trim();

        if (apiToken.isEmpty || email.isEmpty || instanceUrl.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Jira API token, email, and instance URL are required',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        instanceUrl = instanceUrl.replaceAll(RegExp(r'/+$'), '');
        final credentials = base64Encode(utf8.encode('$email:$apiToken'));
        final uri = Uri.parse('$instanceUrl/rest/api/3/myself');

        try {
          final response = await http.get(
            uri,
            headers: {
              'Authorization': 'Basic $credentials',
              'Accept': 'application/json',
            },
          ).timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            final displayName = body['displayName']?.toString() ?? 'unknown';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected as $displayName',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Jira API returned ${response.statusCode}. Verify credentials and URL.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Jira connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'linear') {
        final apiKey = (config.settings['apiKey'] ?? config.settings['api.token'] ?? config.settings['token'] ?? '').toString().trim();

        if (apiKey.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Linear API key is missing',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final uri = Uri.parse('https://api.linear.app/v1/graphql');

        try {
          final response = await http.post(
            uri,
            headers: {
              'Authorization': apiKey,
              'Content-Type': 'application/json',
            },
            body: jsonEncode({
              'query': 'query { viewer { id name } }',
            }),
          ).timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            if (body['errors'] != null) {
              final errors = body['errors'] as List;
              final errorMsg = errors.isNotEmpty ? errors.first['message'] : 'GraphQL error';
              return Response.badRequest(
                body: Body.fromString(
                  jsonEncode({
                    'error': 'Connection failed',
                    'details': 'Linear GraphQL error: $errorMsg',
                  }),
                  mimeType: MimeType.json,
                ),
              );
            }
            final viewerName = body['data']?['viewer']?['name']?.toString() ?? 'unknown';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected as $viewerName',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Linear API returned ${response.statusCode}. Verify API key.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Linear connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'discord') {
        final botToken = (config.settings['botToken'] ?? config.settings['api.token'] ?? config.settings['token'] ?? '').toString().trim();
        final guildId = (config.settings['guildId'] ?? '').toString().trim();

        if (botToken.isEmpty || guildId.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Discord bot token and guild ID are required',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        final uri = Uri.parse('https://discord.com/api/v10/guilds/$guildId');

        try {
          final response = await http.get(
            uri,
            headers: {
              'Authorization': 'Bot $botToken',
              'Accept': 'application/json',
            },
          ).timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            final guildName = body['name']?.toString() ?? 'unknown guild';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected to server: $guildName',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Discord API returned ${response.statusCode}. Verify bot token and guild ID.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'Discord connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      if (config.id == 'gitlab') {
        final apiToken = (config.settings['apiToken'] ?? config.settings['api.token'] ?? config.settings['token'] ?? '').toString().trim();
        var instanceUrl = (config.settings['instanceUrl'] ?? config.baseUrl ?? '').toString().trim();

        if (apiToken.isEmpty || instanceUrl.isEmpty) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'GitLab API token and instance URL are required',
              }),
              mimeType: MimeType.json,
            ),
          );
        }

        instanceUrl = instanceUrl.replaceAll(RegExp(r'/+$'), '');
        final uri = Uri.parse('$instanceUrl/api/v4/user');

        try {
          final response = await http.get(
            uri,
            headers: {
              'PRIVATE-TOKEN': apiToken,
              'Accept': 'application/json',
            },
          ).timeout(const Duration(seconds: 10));

          if (response.statusCode == 200) {
            final body = jsonDecode(response.body) as Map<String, dynamic>;
            final username = body['username']?.toString() ?? 'unknown';
            return Response.ok(
              body: Body.fromString(
                jsonEncode({
                  'data': {
                    'status': 'connected',
                    'message': 'Successfully connected as $username',
                  },
                }),
                mimeType: MimeType.json,
              ),
            );
          }

          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'GitLab API returned ${response.statusCode}. Verify API token and instance URL.',
              }),
              mimeType: MimeType.json,
            ),
          );
        } catch (e) {
          return Response.badRequest(
            body: Body.fromString(
              jsonEncode({
                'error': 'Connection failed',
                'details': 'GitLab connectivity test failed: $e',
              }),
              mimeType: MimeType.json,
            ),
          );
        }
      }

      // Fallback for other providers (Generic ping or mock)
      await Future.delayed(const Duration(seconds: 1));

      bool success = true;
      String? errorMessage;

      if (!config.isActive) {
        success = false;
        errorMessage = 'Provider is not active';
      } else if (config.baseUrl.isEmpty) {
        success = false;
        errorMessage = 'Base URL is missing';
      }

      if (success) {
        return Response.ok(
          body: Body.fromString(
            jsonEncode({
              'data': {
                'status': 'connected',
                'message': 'Successfully pinged ${config.name}',
              },
            }),
            mimeType: MimeType.json,
          ),
        );
      } else {
        return Response.badRequest(
          body: Body.fromString(
            jsonEncode({'error': 'Connection failed', 'details': errorMessage}),
            mimeType: MimeType.json,
          ),
        );
      }
    } catch (e) {
      return Response.badRequest(
        body: Body.fromString(
          jsonEncode({
            'error': 'Invalid request body',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }

  Future<Response> getSystemSettings(Request request) async {
    final result = await _metadata.getSystemSettings.execute();
    return result.fold(
      (failure) => Response.internalServerError(
        body: Body.fromString(
          jsonEncode({
            'error': 'Failed to fetch system settings',
            'details': failure.message,
          }),
          mimeType: MimeType.json,
        ),
      ),
      (settings) => Response.ok(
        body: Body.fromString(
          jsonEncode({'data': settings}),
          mimeType: MimeType.json,
        ),
      ),
    );
  }

  Future<Response> saveSystemSettings(Request request) async {
    try {
      final bodyStr = await request.readAsString();
      final data = jsonDecode(bodyStr) as Map<String, dynamic>;
      final settings = data.map((key, value) => MapEntry(key, value.toString()));

      final result = await _metadata.saveSystemSettings.execute(settings);
      return result.fold(
        (failure) => Response.internalServerError(
          body: Body.fromString(
            jsonEncode({'error': failure.message}),
            mimeType: MimeType.json,
          ),
        ),
        (_) {
          return Response.ok(
            body: Body.fromString(
              jsonEncode({'success': true}),
              mimeType: MimeType.json,
            ),
          );
        },
      );
    } catch (e) {
      return Response.badRequest(
        body: Body.fromString(
          jsonEncode({
            'error': 'Invalid request body',
            'details': e.toString(),
          }),
          mimeType: MimeType.json,
        ),
      );
    }
  }
}
